flyway {
    url = "jdbc:postgresql://localhost:5433/matchPoint"
    user = "flyway_user"
    password = "flyway_password"
    locations = "filesystem:src/main/resources/migrations"
}
db {
  url = "jdbc:postgresql://localhost:5433/matchpoint"
  user = "admin"
  password = "admin"
}