spring.datasource.url=jdbc:postgresql://localhost:5433/matchPoint
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:migrations

jwt.secret=${JWT_SECRET:ZGV2LW9ubHktc2VjcmV0LWNoYW5nZS1iZWZvcmUtZGVwbG95aW5nLXRlbmNoYXJzb21l}
jwt.expiration.ms=${JWT_EXPIRATION_MS:604800000}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dpgvqziul}
cloudinary.api-key=${CLOUDINARY_API_KEY:334955724746665}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:-2pPWcUdyUxwuJPyP7acAs1m0YA}
cloudinary.rackets-prefix=${CLOUDINARY_RACKETS_PREFIX:rackets}