spring.datasource.url=jdbc:postgresql://localhost:5433/matchPoint
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:migrations

jwt.secret=${JWT_SECRET:ZGV2LW9ubHktc2VjcmV0LWNoYW5nZS1iZWZvcmUtZGVwbG95aW5nLXRlbmNoYXJzb21l}
jwt.expiration.ms=${JWT_EXPIRATION_MS:604800000}